add web-tr

diff --git a/.github/workflows/openclash_rule.yml b/.github/workflows/openclash_rule.yml
--- a/.github/workflows/openclash_rule.yml
+++ b/.github/workflows/openclash_rule.yml
@@ -57,6 +57,37 @@ jobs:
           EOF
           rm pi-hole-torrent.txt
 
+          echo "Downloading Pi-hole Torrent Web Blocklist..."
+          curl -sSf -o pi-hole-torrent.txt https://raw.githubusercontent.com/im-sm/Pi-hole-Torrent-Blocklist/main/all-torrent-websites.txt
+
+          if [ ! -f pi-hole-web-torrent.txt ]; then
+              echo "Failed to download the torrent blocklist."
+              exit 1
+          fi
+
+          # Process the file using Python
+          python3 - <<EOF
+          import re
+          import yaml
+
+          with open("pi-hole-web-torrent.txt", "r") as file:
+              input_text = file.read()
+
+          
+          # Ekstraksi domain hanya dua bagian terakhir (suffix) dengan regex
+          payload_lines = re.findall(r"[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", input_text)
+          suffix_only = [f"+.{'.'.join(line.split('.')[-2:])}" for line in payload_lines]
+
+          
+          # Simpan hasil ke file YAML
+          data = {"payload": sorted(set(suffix_only))}  # Hilangkan duplikasi
+          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)
+
+          with open("tr-site.yaml", "w") as file:
+              file.write(yaml_output)
+          EOF
+          rm pi-hole-web-torrent.txt
+
           
           echo "Downloading oisd nsfw source list..."
           curl -sSf -o oisd-nsfw.txt https://nsfw.oisd.nl
